language: go
go:
- '1.10'
services:
- docker 
env:
  global:
  - secure: r6+GLxKdWvuYKKsG7lXgdrI+QRUIfs8ZoeAV5Qlb6OyThuaIbLS9rqneAUbicNEmBbUhFyKjG7e/SFnyeqqD25UrApeJmeJv7rAOwGPZfIo8Tt/fi9icmUNO47lF8lzWTAZdVj5GuahBbR8kB0WurfmoCwn9fbQdXr7+YfsoZVuj4akjERZVLj+ISwK1AL2MCs6fF+2M0cmLuTNtEuBxZtdxYx9AbbJkI6z9sqw8IULuOqaVo1oIPxFNe4oKHQEZhc68w2Y01feAk462ttaEEPb3g3XMZSjuQMiMkbbigW8s3Fr7Y9D+EZ2Tplp/g9tUzaZlUSU85icXZfg8oeSWXJ6krHLC71RnFSvwtPdkouL9D17j2MQjjrDEBlQX61CGak8KQMxFIqoEOxmobWGskMHoBjCIZbXIic4mtXt0k32lR7vOqoZWGmhRPfWxRjc8lXUmFIyfSR0NWWxt38Y+MaOUO8ZQ9TUvW5S8450rAkN27vnwe//rFKMBG/cChbUk4uxwg7fsy50eMYfW3bSx+s4Kt0L9pTCQwNArRV65aHTxKaBpeaaEKGwF1pTDCLC0RVn7Xpj67549+sB8Fp0Ttb/W08lYwiR8u7cjKLJbzTZzIBfDoxbymNdceZjE9Ua/PM0qQn+JHGKDCBYl42jFHcuGkDBEk/eWJQHa6CTCdr8= # DOCKER_USER
  - secure: JoxLEU9sZUDi5eOOT9FMUt54bkEto5Ppd/zJ9zHY4nFBX1goB/0SLa3XVl9ygTj+W+kc3DCj+DO54jqFi9B1QjeINga0/hM8WsCs+kgXMGf6RgyGXClWqUhTxs7ib1uNKXJk533VW4mGmu2jGGNyZhXgQOUq2c3tKXd9xf52twfFQSpqcBbQzhsZpyeAXDHisRDmmU89vZkUG2nnjct8G4ygpMB2+x189VM9Asoy1SorUsuoVuXBgmajtRxSTHAsGq7fG9/xbRY7KVpDPHY+j9aFBYKiHRqpdL9tiQyHdfLpMOYq7IDTyZkM2iljt/L0KVl9qHXbo8P7hAEkik5BkSqNooN06Y/V9IwoJSqtO0iqCSWBjTPJQrTI+IZh2MXzytpv3QPQqxA3BYOasnW+rCvQ2sK8hNeHJIUWa4vRdjn+bEjhUCOpp2rNlxwZo5VTTgkBdCj/sstFn6ARaqRqEt5ACTcOGSZGkiCM3tzCSe3D2aGMfjMkohbzlOHmdtpUNmOJfcZKUFQf/fhCgoebWNv8tvEPioH7zLY1zHpZVKoJoyotr1iJ4iZdrwAa6J42eNRvnXz8xVVUXwBMkdtUWsaFwhw0m/hOG39GaWCnCQygS+R17GxM/fKKwT4Q+l6ZWtjtENn0Rz/cIufJLhzTT4iET4hkf9vtCytHVk48nzU= # DOCKER_PASSWORD
  - COMMIT=${TRAVIS_COMMIT::8}
  
  
before:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - export REPO=admarcel/go_http_server
  
script:
  - docker build -f Dockerfile -t "$REPO:$COMMIT" .
  


after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  
  
  
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
